##
## xy_from_visit_config.yaml
##

# This is the master catalog you are converting, local path & name
input_catalog:
  # catalog_path: /path/to/your/cat
  path: './'
  # catalog name: master_cat.fits
  name: 'COSMOSWeb_master_v2.0.0-sersic-cgs.fits'
  # RA column name in catalog
  ra_colname: 'RA_MODEL'
  # Dec column name in catalog
  dec_colname: 'DEC_MODEL'
  # Which HDU has info? HDU=2 for ldac, usually 1 otherwise
  hdu: 1

# Path to resampled mosaics
visit_mosaic_path: '/n23data2/mfranco/jwst/COSMOS-Web_jan_2024/products/pipeline_level3_better_stripping_jhat/f150w/'

# Parameters for Max Franco-format visit name lists
coord_files:
  # Path to visit name lists
  path: './'
  # Names of visit name lists; hopefully, names include bandpass!
  names: ['coords_f115w_CW_JAN2024.txt', 'coords_f150w_CW_JAN2024.txt', 'coords_f277w_CW_JAN2024.txt', 'coords_f444w_CW_JAN2024.txt']

# Bandpass to use: any of f115w, f150w, f277w, f444w
bandpass: 'f150w'

# Output catalog name
output_catalog:
  # Desired output path
  path: './'
  # Desired output name
  name: 'test_xy.fits'
  # List of columns from original master cat to save
  extra_cols: ['id', 'AREA', 'RADIUS', 'RADIUS_err',
  'AXRATIO', 'AXRATIO_err', 'E1', 'E1_err', 'E2', 'E2_err', 'TILE',
  'FLAG_STAR_JWST', 'source_id', 'FLAG_STAR_HSC']
